# Generated by Django 2.0.5 on 2018-06-01 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180601_0637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
